Repository OnionUI/Onion, pull requests merged in 2023-12, with the labels that each got.

#1301 FEAT: multidisc playlist (.m3u) generator
  src/tweaks/appstate.h
  src/tweaks/menus.h
  src/tweaks/tools.h
  src/tweaks/tools_defs.h
  static/build/.tmp_update/script/cue_gen.sh
  static/build/.tmp_update/script/m3u_gen.sh
  static/build/RetroArch/.retroarch/cores/mednafen_pcfx_libretro.info
Labels: enhancement

#1300 FEAT: App list sorting tool (asc/desc A-Z)
  src/tweaks/menus.h
  src/tweaks/tools.h
  src/tweaks/tools_defs.h
  static/build/.tmp_update/script/app_sorter.sh
Labels: enhancement

#1270 FEAT: Integrate theme, favorites, and recent list functionalities to be profile-specific.
  static/packages/App/Guest Mode/App/Guest_Mode/launch.sh
Labels: enhancement

#1276 Update ko.lang
  static/build/miyoo/app/lang/ko.lang
Labels: localization

#1228 Package Manager: Auto select emulators that has roms present
  src/packageManager/apply.h
  src/packageManager/changes.h
  src/packageManager/fileActions.h
  src/packageManager/globals.h
  src/packageManager/keystateHandler.h
  src/packageManager/listActions.h
  src/packageManager/packageManager.c
  src/packageManager/render.h
  src/packageManager/res/changed.png
  src/packageManager/res/has_roms.png
  src/packageManager/summary.h
Labels: enhancement

#1134 FEAT: Add blue light filter to tweaks
  src/bootScreen/Makefile
  src/common/system/settings.h
  src/keymon/keymon.c
  src/tweaks/actions.h
  src/tweaks/appstate.h
  src/tweaks/formatters.h
  src/tweaks/menus.h
  src/tweaks/tweaks.c
  src/tweaks/values.h
  static/build/.tmp_update/bin/disp_init
  static/build/.tmp_update/runtime.sh
  static/build/.tmp_update/script/blue_light.sh
Labels: enhancement

#1179 FEAT: PWM control
  src/common/system/settings.h
  src/tweaks/actions.h
  src/tweaks/formatters.h
  src/tweaks/menus.h
  src/tweaks/values.h
  static/build/.tmp_update/bin/MainUI-283-clean
  static/build/.tmp_update/bin/MainUI-283-expert
  static/build/.tmp_update/bin/MainUI-354-clean
  static/build/.tmp_update/bin/MainUI-354-expert
  static/build/.tmp_update/runtime.sh
  static/configs/.tmp_update/config/.pwmfrequency
Labels: enhancement

#1241 I18N: Added Norwegian language
  static/build/miyoo/app/lang/no.lang
  static/build/miyoo/app/lang/no.lang.short
Labels: localization

#1193 Fix the sighandler in MainUI
  static/build/.tmp_update/bin/MainUI-283-clean
  static/build/.tmp_update/bin/MainUI-283-expert
  static/build/.tmp_update/bin/MainUI-354-clean
  static/build/.tmp_update/bin/MainUI-354-expert
Labels: MainUI

#1253 FEAT: Add wrapper for global GUI keyboard support.
  lib/libkbinput.so
  src/common/components/kbinput_wrapper.h
  src/tweaks/Makefile
  src/tweaks/actions.h
  src/tweaks/menus.h
  src/tweaks/tweaks.c
Labels: enhancement

#1206 FEAT: Add VNC feature to tweaks
  src/common/components/list.h
  src/tweaks/appstate.h
  src/tweaks/network.h
  static/build/.tmp_update/bin/vncserver
  static/build/.tmp_update/lib/libvncserver.so.1
  static/build/.tmp_update/runtime.sh
Labels: enhancement

#1237 Update 01-amstrad-cpc.md
  website/docs/04-emulators/02-consoles/01-amstrad-cpc.md
Labels: documentation

#1238 Update 09-commodore-64.md
  website/docs/04-emulators/02-consoles/09-commodore-64.md
Labels: documentation

#1239 Update 18-nec-pc-engine-sgfx.md
  website/docs/04-emulators/02-consoles/18-nec-pc-engine-sgfx.md
Labels: documentation

#1240 Update 03-nec-turbografx-cd.md
  website/docs/04-emulators/04-add-ons/03-nec-turbografx-cd.md
Labels: documentation

#1245 Update 09-commodore-64.md
  website/docs/04-emulators/02-consoles/09-commodore-64.md
Labels: documentation

#1244 Update 12-commodore-vic-20.md
  website/docs/04-emulators/02-consoles/12-commodore-vic-20.md
Labels: documentation

#1299 FEAT: Add screen recorder as a tool (Not for game footage)
  src/common/system/settings.h
  src/common/utils/file.c
  src/common/utils/file.h
  src/keymon/keymon.c
  src/tweaks/actions.h
  src/tweaks/appstate.h
  src/tweaks/menus.h
  src/tweaks/tools.h
  static/build/.tmp_update/bin/ffmpeg
  static/build/.tmp_update/lib/libx264.so.155
  static/build/.tmp_update/res/rec.png
  static/build/.tmp_update/script/screen_recorder.sh
Labels: enhancement

#1211 Add Hungarian lang files
  static/build/miyoo/app/lang/hu.lang
  static/build/miyoo/app/lang/hu.lang.short
Labels: localization

#1258 Update screen-capture-toolkit.md (link fix)
  website/docs/07-apps/02-community-apps/screen-capture-toolkit.md
Labels: documentation

#1330 FIX: Blue light filter improvements
  src/common/components/list.h
  src/common/system/settings.h
  src/keymon/keymon.c
  src/tweaks/actions.h
  src/tweaks/appstate.h
  src/tweaks/formatters.h
  src/tweaks/menus.h
  src/tweaks/tweaks.c
  static/build/.tmp_update/runtime.sh
  static/build/.tmp_update/script/blue_light.sh
Labels: enhancement

#1236 FEAT: Mute BGM in Tweaks
  src/common/system/settings.h
  src/tweaks/actions.h
  src/tweaks/menus.h
  src/tweaks/tweaks.c
  static/build/.tmp_update/runtime.sh
Labels: enhancement

#1335 FEAT: Add option to disable time restore
  static/build/.tmp_update/runtime.sh
Labels: enhancement
