Repository OnionUI/Onion, pull requests merged in 2023-10, with the labels that each got.

#1180 DOCS: Fix issues with installation pages
  website/docs/01-getting-started/01-installation/01-fresh-install.mdx
  website/docs/01-getting-started/01-installation/02-upgrading.mdx
Labels: documentation

#1177 FIX : last fixes before 4.2.0
  static/build/.tmp_update/bin/sqlite3
  static/build/.tmp_update/script/netplay/easy-netplay_client.sh
  static/build/.tmp_update/script/netplay/easy-netplay_client_pokemon.sh
  static/build/.tmp_update/script/netplay/easy-netplay_server.sh
  static/build/.tmp_update/script/netplay/easy-netplay_server_pokemon.sh
  static/build/.tmp_update/script/scraper/menu.sh
  static/build/.tmp_update/script/stop_audioserver.sh
  static/build/RetroArch/.retroarch/cores/gpsp_libretro.so
  static/build/RetroArch/.retroarch/overlay/GB-GBC/Frame-Grid/GBC-100.cfg
  static/build/RetroArch/.retroarch/overlay/GB-GBC/Frame-Grid/GBC-100.png
  static/build/RetroArch/.retroarch/overlay/GB-GBC/Frame-Grid/GBC-70.cfg
  static/build/RetroArch/.retroarch/overlay/GB-GBC/Frame-Grid/GBC-70.png
  static/build/RetroArch/.retroarch/overlay/GB-GBC/Frame-Grid/PALGBP+D20.cfg
  static/build/RetroArch/.retroarch/overlay/GB-GBC/Frame-Grid/PALGBP+D20.png
  static/packages/App/Music Player (GMU)/App/Gmu/.config/gmu/gmu.conf
  static/packages/App/Music Player (GMU)/App/Gmu/.local/share/gmu/playlist.m3u
  static/packages/App/Music Player (GMU)/App/Gmu/config.json
  static/packages/App/Music Player (GMU)/App/Gmu/cpufreq.sh
  static/packages/App/Music Player (GMU)/App/Gmu/frontends/sdl.so
  static/packages/App/Music Player (GMU)/App/Gmu/gmu.bin
  static/packages/App/Music Player (GMU)/App/Gmu/gmu.bmp
  static/packages/App/Music Player (GMU)/App/Gmu/gmu.miyoo.conf
  static/packages/App/Music Player (GMU)/App/Gmu/gmu.png
  static/packages/App/Music Player (GMU)/App/Gmu/gmuinput.miyoo.conf
  static/packages/App/Music Player (GMU)/App/Gmu/launch.sh
  static/packages/App/Music Player (GMU)/App/Gmu/launch2.sh
  static/packages/App/Music Player (GMU)/App/Gmu/lib/libSDL_gfx.so.15
  static/packages/App/Music Player (GMU)/App/Gmu/lib/libSDL_image-1.2.so.0
  static/packages/App/Music Player (GMU)/App/Gmu/lib/libjpeg.so.62
  static/packages/App/Music Player (GMU)/App/Gmu/lib/libogg.so.0
  static/packages/App/Music Player (GMU)/App/Gmu/lib/libpng.so
  static/packages/App/Music Player (GMU)/App/Gmu/log.txt
  static/packages/App/Music Player (GMU)/App/Gmu/miyoo.keymap
  static/packages/App/Music Player (GMU)/Media/Music/Onion music theme - 01.mp3
  static/packages/App/Music Player (GMU)/Media/Music/Onion music theme - 02.mp3
  static/packages/App/Music Player (GMU)/Media/Music/sample1.mp3
  static/packages/App/Music Player (GMU)/Media/Music/sample2.mp3
  static/packages/Emu/Ports Collection/Emu/PORTS/launch_python2.sh
  static/packages/Emu/Ports Collection/Emu/PORTS/launch_retroarch.sh
  static/packages/Emu/Ports Collection/Emu/PORTS/launch_standalone.sh
  static/packages/Emu/SCUMM (ScummVM)/Emu/SCUMMVM/launch.sh
  static/packages/RApp/Game engine - Open Beats of Rage/RApp/OpenBOR/launch.sh
  static/packages/RApp/PICO-8 (Fake8 standalone)/RApp/PICO/launch.sh
  static/packages/RApp/PICO-8 (Fake8 standalone)/RApp/Roms/PICO/.gitkeep
Labels: bug in onion

#1189 FIX-Update dropbear binary
  static/build/.tmp_update/bin/dropbear
  static/build/.tmp_update/etc/dropbear/.gitkeep
Labels: enhancement

#1170 DOCS: Prepare release notes for 4.2
  website/blog/authors.yml
  website/blog/misc/2023-09-16-website-intro.md
  website/blog/release-notes/2022-07-05-release-notes-3.12.3.md
  website/blog/release-notes/2022-09-10-release-notes-4.0.0.md
  website/blog/release-notes/2023-03-21-release-notes-4.1.0.md
  website/blog/release-notes/2023-09-25-release-notes-4.2.0/assets/banner-release-4.2.png
  website/blog/release-notes/2023-09-25-release-notes-4.2.0/index.mdx
  website/docs/07-apps/02-community-apps/index.mdx
  website/docusaurus.config.js
  website/package-lock.json
  website/package.json
  website/src/components/Card.tsx
  website/src/components/ThemeCard.tsx
  website/src/components/ThemeCollection.tsx
  website/src/style/custom.scss
  website/yarn.lock
Labels: documentation

#1202 FIX: Trigger RetroArch related updates for users on 4.2-RC
  Makefile
Labels: bug in onion

#1194 I18N: Update German translation
  static/build/miyoo/app/lang/de.lang
Labels: localization

#1207 DOCS: Update ssh documentation
  website/docs/07-apps/03-network-features/03-ssh-sftp.md
  website/docs/07-apps/03-network-features/assets/terminal-ssh.png
Labels: documentation

#1208 Update PixelReader to v0.6
  static/packages/App/Ebook Reader (PixelReader)/App/PixelReader/reader
Labels: enhancement

#1209 Fix for a better looking 6x10 Russian font
  static/build/RetroArch/.retroarch/assets/rgui/font/bitmap6x10_rus.bin
Labels: enhancement

#1203 FIX: Move system settings to SD and retain individual device settings
  src/common/system/settings.h
  src/common/theme/load.h
  src/read_uuid/read_uuid.c
  src/tweaks/reset.h
  static/build/.tmp_update/bin/MainUI-283-clean
  static/build/.tmp_update/bin/MainUI-283-expert
  static/build/.tmp_update/bin/MainUI-354-clean
  static/build/.tmp_update/bin/MainUI-354-expert
  static/build/.tmp_update/bin/shutdown
  static/build/.tmp_update/runtime.sh
  static/build/.tmp_update/script/diagnostics/util_snapshot.sh
  static/build/.tmp_update/script/network/wpsclient.sh
  static/dist/miyoo/app/.tmp_update/install.sh
Labels: bug in onion

#1223 FIX: Display settings not applying in 4.2.1
  static/build/.tmp_update/runtime.sh
Labels: bug in onion

#1251 Update syncthing.md
  website/docs/07-apps/02-community-apps/syncthing.md
Labels: documentation
