Repository OnionUI/Onion, pull requests merged in 2024-05, with the labels that each got.

#1525 Add document to commuity app section for FlipClock
  website/docs/07-apps/02-community-apps/flip-clock.md
Labels: documentation

#1540 Update 07-vnc-server.md
  website/docs/07-apps/03-network-features/07-vnc-server.md
Labels: documentation

#1427 MainUI: Disable text shadows
  src/common/theme/render/list.h
  static/build/.tmp_update/bin/MainUI-283-clean
  static/build/.tmp_update/bin/MainUI-283-expert
  static/build/.tmp_update/bin/MainUI-354-clean
  static/build/.tmp_update/bin/MainUI-354-expert
Labels: enhancement

#1459 Fix games larger than 2GB not showing in GameSwitcher
  src/common/utils/file.c
Labels: bug in onion

#1494 Add tree and pippi
  .gitignore
  Makefile
  src/pippi/Makefile
  src/pippi/pippi.c
  src/tree/Makefile
  src/tree/tree.c
Labels: enhancement

#1495 Fix discrepancy between MainUI and Onion volume
  src/common/theme/sound.h
Labels: bug in onion

#1488 Move writing settings to thread.
  src/keymon/keymon.c
Labels: bug in onion

#1541 Fix Easy Netplay when starting through Search
  static/build/.tmp_update/script/netplay/easy-netplay_server.sh
Labels: bug in onion

#1579 Skip keymon's force shutdown if runtime is already shutting down
  src/keymon/keymon.c
  static/build/.tmp_update/runtime.sh
Labels: bug in onion

#1582 FIX: Setting Swap L1<>L2 in Drastic breaks Menu Exits
  src/keymon/menuButtonAction.h
  static/packages/Emu/Nintendo - DS (Drastic)/Emu/NDS/launch.sh
Labels: bug in onion

#1593 Improved GB, GBC, and GBA grid overlays
  static/build/RetroArch/.retroarch/overlay/GB-GBC/Frame-Grid/gb_grid.png
  static/build/RetroArch/.retroarch/overlay/GB-GBC/Frame-Grid/gbc_grid.cfg
  static/build/RetroArch/.retroarch/overlay/GB-GBC/Frame-Grid/gbc_grid.png
  static/build/RetroArch/.retroarch/overlay/GBA/gba_3x_grid.cfg
  static/build/RetroArch/.retroarch/overlay/GBA/gba_3x_grid.png
Labels: enhancement
