Repository OnionUI/Onion, pull requests merged in 2024-10, with the labels that each got.

#1643 Add Finnish language
  static/build/miyoo/app/lang/fi.lang
  static/build/miyoo/app/lang/fi.lang.short
Labels: localization

#1640 Add storii.md
  website/docs/07-apps/02-community-apps/storii.md
Labels: documentation

#1648 Add Galician language
  static/build/miyoo/app/lang/gl.lang
  static/build/miyoo/app/lang/gl.lang.short
Labels: localization

#1656 Fix `clock` CPU utilization
  src/clock/Makefile
  src/clock/main.c
Labels: enhancement
