Repository OnionUI/Onion, pull requests merged in 2024-01, with the labels that each got.

#1345 FIX: bgm_mute setting gets deleted by MainUI
  src/common/system/settings.h
  static/build/.tmp_update/runtime.sh
Labels: bug in onion

#1358 Fixed low battery warning overlapping other battery icons
  src/batmon/batmon.c
  src/batmon/batmon.h
  src/common/theme/resources.h
Labels: bug in onion

#1379 French fixes
  static/build/miyoo/app/lang/fr.lang
Labels: localization

#1384 Update es.lang
  static/build/miyoo/app/lang/es.lang
Labels: localization

#1372 Added Romanian languange
  static/build/miyoo/app/lang/ro.lang
  static/build/miyoo/app/lang/ro.lang.short
Labels: localization

#1375 OTA: format release date and size info of new version zip
  static/build/.tmp_update/script/ota_update.sh
Labels: enhancement
